actions:
  - type: "remove"
    selector: ".ad-banner"
  - type: "replace"
    selector: "#old-header"
    newElement: "<header id='new-header'>New Header</header>"
  - type: "insert"
    position: "after"
    target: "body"
    element: "<footer>Footer Content</footer>"
  - type: "alter"
    oldValue: "Machine Learning"
    newValue: "AI"
